### PR TITLE
src/service.c: Add tooltip support.

### PR DESCRIPTION
**Pull request by sunweaver**

### CODE REVIEW

**Comment by sunweaver** [comment]
@flexiondotorg It would be nice to get your feedback on this as a English native speaker. Thanks.

**Comment by sunweaver** [comment]
@flexiondotorg It would be nice to get your feedback on this as a English native speaker. Thanks.

**Review by flexiondotorg — APPROVED** [review]
LGTM

**Comment by sunweaver** [comment]
Sigh. PR not closed automatically. Closed via 5262add58816ac4789a201721293e5bd370e7b8a

**Pull request closed without merging**
