### PR TITLE
Display a zenity warning if the audio settings application is not found

### LINKED ISSUE #12: zenity warning, if audio settings dialog window is not available
If the application providing the audio settings dialog window is not installed, the -sound indicator should fallback to a zenity warning, that informs about the missing application.

### PR DESCRIPTION
**Pull request by tari01**
Fixes #12

### CODE REVIEW

**Comment by sunweaver** [comment]
This needs a clean rebase, possibly after #17 has been merged to master. Not reviewing this now.

**Comment by sunweaver** [comment]
please rebase this PR (#18) now, thanks

**Comment by tari01** [comment]
> please rebase this PR (#18) now, thanks

Now we should be OK.

**Review by sunweaver — APPROVED** [review]
LGTM

**Pull request merged**
